window.processData = {
  id: "root",
  title: "驗收站點 (RCV)",
  description:
    "主要處理的貨物稱為 NYR (Not Yet Receive)。\n作業分為板驗及散驗，需依商品的大小及數量去區分應使用的驗收方式。\n需要觀察當天預計到倉量、碼頭的卸貨量、未卸板數、各板貨態、移倉數量等等來決定散驗及板驗人力的配置。",
  notes:
    "驗收量需大於碼頭的卸貨量，否則會造成碼頭塞車。\n若有多餘人力，需要觀察上架的待上架商品暫存區是否有足夠的貨物可上架，並與上架 Captain 確認是否需要補貨。",
  type: "role",
  isOpen: true,
  layout: "vertical",
  style: {
    bgColor: "bg-slate-50",
    borderColor: "border-slate-800",
    fontFamily: "font-sans",
    titleSize: "text-2xl",
    contentSize: "text-base",
  },
  children: [
    {
      id: "process",
      title: "1.1 散驗作業流程 (Process)",
      description:
        "驗收員會在輸送帶旁的工作台進行商品驗收與決定入庫位置。\n可裝入物流箱的為散貨，無法裝入箱或太大者為板貨。",
      notes:
        "商品品名、外觀、規格是否與系統一致？\n商品是否需要效期、及效期是否超過系統顯示？\n商品最小包裝單位為何？\n外部包裝是否與內部包裝一致？\n若有任何問題則務必通知 PS。",
      type: "process",
      isOpen: true,
      layout: "vertical",
      style: {
        bgColor: "bg-white",
        borderColor: "border-blue-500",
        fontFamily: "font-sans",
        titleSize: "text-xl",
        contentSize: "text-base",
      },
      children: [
        {
          id: "step1",
          title: "步驟 1：啟動輸送帶",
          description: "按下綠色按鈕啟動輸送帶，讓貨到達工作台。",
          type: "step",
          isOpen: false,
          layout: "vertical",
          style: {
            bgColor: "bg-white",
            borderColor: "border-slate-200",
            fontFamily: "font-sans",
            titleSize: "text-lg",
            contentSize: "text-base",
          },
          children: [],
        },
        {
          id: "step2",
          title: "步驟 2：開啟系統",
          description: "打開 worker tool，選擇「入庫」功能。",
          type: "step",
          isOpen: false,
          layout: "vertical",
          style: {
            bgColor: "bg-white",
            borderColor: "border-slate-200",
            fontFamily: "font-sans",
            titleSize: "text-lg",
            contentSize: "text-base",
          },
          children: [],
        },
        {
          id: "step3",
          title: "步驟 3：刷讀條碼",
          description: "依序刷以下條碼：\n1. 工作台條碼\n2. IBC 條碼（麥頭上）\n3. 商品條碼",
          type: "step",
          isOpen: false,
          layout: "vertical",
          style: {
            bgColor: "bg-white",
            borderColor: "border-slate-200",
            fontFamily: "font-sans",
            titleSize: "text-lg",
            contentSize: "text-base",
          },
          children: [],
        },
        {
          id: "step4",
          title: "步驟 4：商品檢核",
          description: "檢查外觀、品名、圖片、效期等是否與系統相符。",
          notes: "⚠️ 效期需大於系統顯示日期，若小於請報警示。",
          type: "step",
          isOpen: false,
          layout: "vertical",
          style: {
            bgColor: "bg-white",
            borderColor: "border-slate-200",
            fontFamily: "font-sans",
            titleSize: "text-lg",
            contentSize: "text-base",
          },
          children: [],
        },
        {
          id: "step5",
          title: "步驟 5：裝箱",
          description: "驗收完成後，將商品放入物流箱內。",
          notes: "⚠️ 注意不要超過限高線，以免造成後續自動倉儲卡貨。",
          type: "step",
          isOpen: false,
          layout: "vertical",
          style: {
            bgColor: "bg-white",
            borderColor: "border-slate-200",
            fontFamily: "font-sans",
            titleSize: "text-lg",
            contentSize: "text-base",
          },
          children: [],
        },
        {
          id: "step6",
          title: "步驟 6：輸入數量與儲位",
          description:
            "在系統輸入數量，選擇要送去的倉庫位置（一樓或二樓）。\n部分商品會自動分配儲位，其他需手動選取。",
          type: "step",
          isOpen: false,
          layout: "vertical",
          style: {
            bgColor: "bg-white",
            borderColor: "border-slate-200",
            fontFamily: "font-sans",
            titleSize: "text-lg",
            contentSize: "text-base",
          },
          children: [],
        },
        {
          id: "step7",
          title: "步驟 7：確認入庫",
          description: "掃物流箱條碼，確認入庫完成。",
          type: "step",
          isOpen: false,
          layout: "vertical",
          style: {
            bgColor: "bg-white",
            borderColor: "border-slate-200",
            fontFamily: "font-sans",
            titleSize: "text-lg",
            contentSize: "text-base",
          },
          children: [],
        },
        {
          id: "step8",
          title: "步驟 8：資料查驗",
          description: "開啟物流箱條碼查驗資料，若正確，點選「入庫」。",
          type: "step",
          isOpen: false,
          layout: "vertical",
          style: {
            bgColor: "bg-white",
            borderColor: "border-slate-200",
            fontFamily: "font-sans",
            titleSize: "text-lg",
            contentSize: "text-base",
          },
          children: [],
        },
        {
          id: "step9",
          title: "步驟 9：完成作業",
          description: "將物流箱推入下方輸送帶，完成本次散驗。",
          type: "step",
          isOpen: false,
          layout: "vertical",
          style: {
            bgColor: "bg-white",
            borderColor: "border-slate-200",
            fontFamily: "font-sans",
            titleSize: "text-lg",
            contentSize: "text-base",
          },
          children: [],
        },
      ],
    },
    {
      id: "node-pallet-root",
      title: "1.2 板驗作業 (Pallet Receiving)",
      description: "負責棧板貨物的驗收、分類與入庫作業。\n區分為廠內用 (RCRT) 與轉出專用 (GCGP/GCGT)。",
      notes:
        "【關鍵績效指標 KPI】\n• Each: HTP 300\n• Pallet: HTP 1800\n\n【一般規範】\n• 板驗人員標示請用「白色膠帶」。\n• 驗效期以「抽查四角與中間」方式進行，以防過期混貨。\n• 食品、母嬰、洗浴等與人體接觸商品，「禁止於效期處貼標」或塗改。\n\n【重量限制】\n• 一般板：800kg\n• 液體類：可至 1000kg (但轉出不得超過 800kg)",
      type: "process",
      isOpen: true,
      layout: "vertical",
      style: {
        bgColor: "bg-white",
        borderColor: "border-purple-500",
        fontFamily: "font-sans",
        titleSize: "text-xl",
        contentSize: "text-base",
      },
      children: [
        {
          id: "pallet-common-process",
          title: "1.2.1 板驗作業流程",
          description: "所有板驗貨物皆須執行的標準系統操作步驟。",
          type: "process",
          isOpen: true,
          layout: "vertical",
          style: {
            bgColor: "bg-purple-50",
            borderColor: "border-purple-300",
            fontFamily: "font-sans",
            titleSize: "text-lg",
            contentSize: "text-base",
          },
          children: [
            {
              id: "p-step1",
              title: "① 開啟系統",
              description: "開啟 WMS 系統驗收功能。",
              type: "step",
              isOpen: false,
              layout: "vertical",
              style: {
                bgColor: "bg-white",
                borderColor: "border-slate-200",
                fontFamily: "font-sans",
                titleSize: "text-lg",
                contentSize: "text-base",
              },
              children: [],
            },
            {
              id: "p-step2",
              title: "② 刷入工作檯",
              description: "刷入工作檯分類條碼。",
              type: "step",
              isOpen: false,
              layout: "vertical",
              style: {
                bgColor: "bg-white",
                borderColor: "border-slate-200",
                fontFamily: "font-sans",
                titleSize: "text-lg",
                contentSize: "text-base",
              },
              children: [],
            },
            {
              id: "p-step3",
              title: "③ 刷入 IBC",
              description: "刷入待驗 IBC 條碼。",
              type: "step",
              isOpen: false,
              layout: "vertical",
              style: {
                bgColor: "bg-white",
                borderColor: "border-slate-200",
                fontFamily: "font-sans",
                titleSize: "text-lg",
                contentSize: "text-base",
              },
              children: [],
            },
            {
              id: "p-step4",
              title: "④ 查詢屬性",
              description: "查詢是否為移轉貨物 (Cross Dock)。",
              notes: "⚠️ 轉出貨優先處理！若到貨量少於應轉出量，則全數設為移轉貨。",
              type: "step",
              isOpen: false,
              layout: "vertical",
              style: {
                bgColor: "bg-white",
                borderColor: "border-slate-200",
                fontFamily: "font-sans",
                titleSize: "text-lg",
                contentSize: "text-base",
              },
              children: [],
            },
            {
              id: "p-step5",
              title: "⑤ 盤點",
              description: "盤點貨物數量與效期。",
              notes: "務必檢查四角與中間貨物，防止混入過期品。",
              type: "step",
              isOpen: false,
              layout: "vertical",
              style: {
                bgColor: "bg-white",
                borderColor: "border-slate-200",
                fontFamily: "font-sans",
                titleSize: "text-lg",
                contentSize: "text-base",
              },
              children: [],
            },
            {
              id: "p-step6",
              title: "⑥ 輸入數量",
              description: "於系統輸入實際驗收數量。",
              type: "step",
              isOpen: false,
              layout: "vertical",
              style: {
                bgColor: "bg-white",
                borderColor: "border-slate-200",
                fontFamily: "font-sans",
                titleSize: "text-lg",
                contentSize: "text-base",
              },
              children: [],
            },
            {
              id: "p-step7",
              title: "⑦ 選擇物流箱分類",
              description: "選擇物流箱分類：\n• RCRT：廠內用\n• GCGP：轉出專用",
              notes:
                "⚠️ 同一棧板若部分需移轉，應「優先處理移轉貨」。\nGCGP 填滿後再進行 RCRT，兩者標籤可共用一板。",
              type: "step",
              isOpen: true,
              layout: "vertical",
              style: {
                bgColor: "bg-amber-50",
                borderColor: "border-amber-500",
                fontFamily: "font-sans",
                titleSize: "text-lg",
                contentSize: "text-base",
              },
              children: [
                {
                  id: "proc_rcrt",
                  title: "若為 RCRT (廠內用)",
                  description:
                    "⑩ 於標示上寫預計轉出位置與碼頭號。\n⑪ 貼至棧板側邊並換上對應日高角錐。\n⑫ 完成入庫。",
                  notes: "【RCRT 規範】\n• 一個標示對應一種貨物。",
                  type: "step",
                  isOpen: true,
                  layout: "vertical",
                  style: {
                    bgColor: "bg-emerald-50",
                    borderColor: "border-emerald-500",
                    fontFamily: "font-sans",
                    titleSize: "text-base",
                    contentSize: "text-sm",
                  },
                  children: [],
                },
                {
                  id: "proc_gcgp",
                  title: "若為 GCGP (轉出專用)",
                  description:
                    "⑩ 於 Cross Dock 工作表輸入實際驗收數量、移轉數量、板數。\n⑪ 於標籤上寫上數量，並貼上 GCGP 標籤至棧板側邊。\n⑫ 換上對應日的高角錐，並套上「紅白相間扁角錐」。",
                  notes:
                    "【GCGP 規範】\n• 每棧板最多五種貨物。\n• 標籤必須對應實際貨物並寫上數量。\n• 同一棧板 GCGP 貨物須為「相同轉出位置」，不同位置需分板。",
                  type: "step",
                  isOpen: true,
                  layout: "vertical",
                  style: {
                    bgColor: "bg-rose-50",
                    borderColor: "border-rose-500",
                    fontFamily: "font-sans",
                    titleSize: "text-base",
                    contentSize: "text-sm",
                  },
                  children: [],
                },
              ],
            },
            {
              id: "p-step8",
              title: "⑧ 確認物流箱",
              description: "刷入對應條碼，並點選物流箱號碼確認。",
              type: "step",
              isOpen: false,
              layout: "vertical",
              style: {
                bgColor: "bg-white",
                borderColor: "border-slate-200",
                fontFamily: "font-sans",
                titleSize: "text-lg",
                contentSize: "text-base",
              },
              children: [],
            },
            {
              id: "p-step9",
              title: "⑨ 完成驗收",
              description: "點選「入庫」完成系統驗收作業。",
              type: "step",
              isOpen: false,
              layout: "vertical",
              style: {
                bgColor: "bg-white",
                borderColor: "border-slate-200",
                fontFamily: "font-sans",
                titleSize: "text-lg",
                contentSize: "text-base",
              },
              children: [],
            },
          ],
        },
      ],
    },
    {
      id: "node-h99txb4",
      title: "新子區塊",
      description: "請填寫說明...",
      type: "step",
      isOpen: true,
      layout: "vertical",
      style: {
        bgColor: "bg-white",
        borderColor: "border-slate-200",
        fontFamily: "font-sans",
        titleSize: "text-lg",
        contentSize: "text-base",
      },
      children: [],
    },
  ],
};

window.layoutOptions = [
  {
    value: "vertical",
    label: "直向堆疊",
    description: "說明在上、注意事項在下，保持條列分明。",
  },
  {
    value: "side-notes",
    label: "左右分欄",
    description: "說明在左、注意事項在右，便於對照重點。",
  },
];
